### ISSUE TITLE
Unicode messed up indenting

### ISSUE THREAD

**Issue by tk3369** [julia-vscode/DocumentFormat.jl#140]
I have code in HoJBot.jl that is formatted badly -- the return statement is flushed left.

It seems that having unicode character/emoji confuses it...
```
function reactions(::GoodbyeReactor, m::Message)
    if contains_any(m.content, REACT_WORDS[:goodbye])
    return ['👋']
    end
    return NO_REACTION
end
```

**Comment by davidanthoff** [comment]
The formatter is not in good shape these days... We hope to swap in JuliaFormatter.jl soon (TM) :)

**Comment by tk3369** [comment]
Oh ok. Thanks for the update.
