### ISSUE TITLE
README mentions calling format with String, but that is not defined

### ISSUE THREAD

**Issue by joaocmd** [julia-vscode/DocumentFormat.jl#151]
Example:

```julia
code = read("file.jl", String)
format(code)
```

Throws error:

```
ERROR: MethodError: no method matching format(::String)
Closest candidates are:
  format(::AbstractPath) at ~/.julia/packages/DocumentFormat/bFNbs/src/DocumentFormat.jl:20
```

**Comment by davidanthoff** [comment]
Well, the README also says this package is deprecated :) At the moment it is still serving some legacy lifting for the VS Code extension CI story, but it really is just a slim shim around JuliaFormatter.jl, which is the package everyone should be using.

**Comment by joaocmd** [comment]
Thank you, I came here from a thread on Julia forums but after reading your source code I ended up just using JuliaFormatter.jl anyway :)
