### ISSUE TITLE
AST transforms

### ISSUE THREAD

**Issue by domluna** [julia-vscode/DocumentFormat.jl#23]
What are your thoughts on syntax transforming the AST prior to formatting?

A couple of examples:

1.

```
for i = 1:10

 INTO

for i in 1:10
```

2.

```
@doc “doc” ->
function f()
	…
end

INTO

“””doc”””
function f()
	…
end
```

These would be based on style guidelines.

**Comment by ZacLN** [comment]
Personally I'm all for this sort of transformation, make a PR!
