### ISSUE TITLE
Code reformat removes \\ in latex comments

### ISSUE THREAD

**Issue by classner** [julia-vscode/DocumentFormat.jl#37]
Hi!

Thanks for creating this powerful package! I'm using the language server with the Emacs frontend and am observing automatic removal of double-backslashes from latex comments, e.g., a comment like

```
"""
    Some-function

Calculates ``a \\in b``.
"""
```

gets reformatted to

```
"""
    Some-function

Calculates ``a \in b``.
"""
```

Even though I'd also prefer the latter version in principle ;-), only the former works with Documenter.jl.

**Comment by davidanthoff** [comment]
I can replicate that in VS Code as well.

**Comment by ZacLN** [comment]
I don't think I'll be able to fix this quickly so putting it to the backlog

**Comment by davidanthoff** [comment]
I think this is the one issue I'm pretty nervous about :) It does look like a bug that can actually introduce very subtle errors into user code... @ZacLN do you think there is a chance we can fix this for v0.12.0, or did you think of pushing this back to a much later release?

**Comment by ZacLN** [comment]
I don't have  the time to delve into it for the next couple of weeks (until the start of July). I'll disable the affected code

**Comment by davidanthoff** [comment]
That sounds like a good plan!
