### ISSUE TITLE
StringIndexError

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/DocumentFormat.jl#42]
Details [here](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22Name%22%3A%22julia-vscode-dev%22%2C%22SubscriptionId%22%3A%226803c4ed-bcb4-41d4-bceb-7faf5e7a3469%22%2C%22ResourceGroup%22%3A%22Default%22%7D/DataModel/%7B%22eventId%22%3A%2255f5d5d1-a8a7-11e9-b4ea-b79b43346469%22%2C%22timestamp%22%3A%222019-07-17T15%3A26%3A56.912Z%22%2C%22cacheId%22%3A%22839e5318-38cb-41a5-a9e4-5420877d02a8%22%2C%22eventTable%22%3A%22exceptions%22%7D). I'm not posting them because they contain identifiable stuff.

**Comment by ZacLN** [comment]
https://github.com/julia-vscode/DocumentFormat.jl/commit/59317b4353f285abcb8790bd893b22dca554602d

we/I should possibly take this approach (stop indexing into strings, use the underlying UInt8s) elsewhere as well..
