### ISSUE TITLE
Spaces after comma in function declaration should be removed

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/DocumentFormat.jl#51]
For example, `function foo(x,  y)` should be turned into `foo(x, y)`

**Comment by ZacLN** [comment]
Not quite sure I understand this given your example code?

**Comment by waldyrious** [comment]
It seems like [GitHub's markdown processor](https://github.com/github/cmark-gfm) is collapsing multiple spaces inside code blocks — see https://github.com/commonmark/commonmark-spec/issues/532.

For example, if I add multiple spaces between `x` and `y`, the spaces are preserved in code blocks, but not in inline code spans:

    function foo(x,          y)

`function foo(x,          y)`

**Comment by ZacLN** [comment]
Ah, gotcha!

**Comment by davidanthoff** [comment]
Yes, that is what I meant :)
