### ISSUE TITLE
Don't move things across lines

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/DocumentFormat.jl#53]
For example, it changes
```
makedocs(
	modules = [StringBuilders],
	sitename = "StringBuilders.jl",
	pages = [
        "Home" => "index.md"
    ]
)
```
to
```
makedocs(modules = [StringBuilders],
	sitename = "StringBuilders.jl",
	pages = [
        "Home" => "index.md"
    ])
```
I kind of feel the removal of the line break after `makedocs(` in this case is not really necessary?

I'm less sure about the final parenthesis. Should that really not stay on its own line at the same indent as `makedocs`? Not sure...

**Comment by waldyrious** [comment]
FWIW, a rule of thumb I find useful to reason about these things is to apply the same logic:
- to all bracket types (e.g. `<{([` / `])}>`)
- regardless of their semantic function (e.g. wrapping function parameters, delimiting code blocks, etc.), and
- to both ends of a bracket pair (i.e. either the content is placed inline, surrounded by the brackets, or the content is placed in an indented block on its own, with the brackets above and below with one less indentation level.)

That makes it a single rule that is never ambiguous nor context-dependent; it's easy for machines and humans alike to apply and verify; and it's visually helpful to represent the structure of the code in a consistent manner.

So in this case the result would be exactly as the top code block, or

```
makedocs(
	modules = [StringBuilders],
	sitename = "StringBuilders.jl",
	pages = ["Home" => "index.md"]
)
```

**Comment by davidanthoff** [comment]
I kind of feel that DocumentFormat should leave line breaks alone in general? And just fix indenting and white spaces?

**Comment by norru** [comment]
I was about to post a bug report saying `DocumentFormat.jl` doesn't tidy up across lines :) which is causing me to jump between VSC and Atom just to get that done.

I generally expect a "prettyfier" to make my code pretty and tidy and that often requires moving code across lines, which is fine.

I do agree that for @davidanthoff cases there must be an option to disable line break changes.

**Comment by davidanthoff** [comment]
Clearly something that needs to be an option :)
