### ISSUE TITLE
Error when formatting VegaLite.jl

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/DocumentFormat.jl#56]
I get an error that the syntax tree is not identical after formatting when I try to format the whole VegaLite.jl project.

Repo steps:
1. `pkg> dev VegaLite`
2. `pkg> add PkgDev` (I surfaced whole package formatting in that package now)
3. `using PkgDev`
4. `PkgDev.format("VegaLite")`

**Comment by ZacLN** [comment]
Not really fixed, but we now don't apply these edits (and don't error) where they modify the ast. Moving from current project
