### ISSUE TITLE
Formatter foxed by `\n` within function documentation.

### ISSUE THREAD

**Issue by PGS62** [julia-vscode/DocumentFormat.jl#61]
The Format Document command fails to work correctly if I include \n in the documentation section for a function. For example, the code below will be correctly formatted by the formatter:
```
"""
   `function testfunction(x,y)`

returns the sum of `x` and `y`
"""
function testfunction(x,y)
x+y
end
```

But the code below is _not_ formatted correctly - indentation does not happen, though spaces are inserted around the + operator and after the comma.

```
"""
   `function testfunction(x,y)`\n
returns the sum of `x` and `y`
"""
function testfunction(x,y)
x+y
end

```

**Comment by xgdgsc** [comment]
I often see extra 4 space before "function", don' t know if related. It often happens if I forget to put end in the first place and saved once. Then adding end for function doesn' t make it work correctly.
