### ISSUE TITLE
Formatter breaks shebang

### ISSUE THREAD

**Issue by fedario** [julia-vscode/DocumentFormat.jl#80]
Hi,

when adding a Linux shebang to a .jl file, the formatter treats it as a normal comment and inserts a space after the `#`, thereby breaking its functionality.

Example:

`#!/usr/bin/env julia` becomes `# !/usr/bin/env julia` which is not a valid shebang.

**Comment by ZacLN** [comment]
https://github.com/julia-vscode/DocumentFormat.jl/pull/83
